# x: xmin, xmax, steps; y: ymin, ymax, steps; data: normalized open area #generated by flare_coarse_locator_skylut_generator.ipynb on 2021-04-12 18:04:01.997445
import os
import numpy as np
filename=os.path.join(os.path.dirname(os.path.realpath(__file__)),'skylut.npz')
print('skylut',filename)
data=np.load(filename)
