# x: xmin, xmax, steps; y: ymin, ymax, steps; data: normalized open area #generated by flare_coarse_locator_skylut_generator.ipynb on 2021-04-12 18:04:01.997445
from pathlib import Path
import numpy as np
filename = Path(__file__).resolve().parents[1] / 'data' / 'skylut.npz'
print('skylut',filename)
data=np.load(filename)
