# x: xmin, xmax, steps; y: ymin, ymax, steps; data: normalized open area #generated by flare_coarse_locator_skylut_generator.ipynb on 2021-04-12 18:04:01.997445
from pathlib import Path
import numpy as np
import h5py
filename = Path(__file__).resolve().parents[1] / 'data' / 'skylut.h5'
#filename2 = Path(__file__).resolve().parents[1] / 'data' / 'skylut.h5'

hdf=h5py.File(filename,'r')
#print('skylut',filename)
#d=np.load(filename)
data={'x':np.array(hdf.get('x')),
        'y':np.array(hdf.get('y')),
        'skylut':np.array(hdf.get('skylut'))
        }

#hf.create_dataset('x',data=d['x'])
#hf.create_dataset('y',data=d['y'])
#hf.create_dataset('skylut',data=d['skylut'])
#hf.close()
#print(data)

